before_script:
  - dnf -y update && dnf -y install docker
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.splentity.com

variables:
  IMAGE_HUGO: registry.splentity.com/openblox/ci-build-environment/ob-hugo:latest
  IMAGE_OB: registry.splentity.com/openblox/ci-build-environment/ob:latest

build:
  stage: build
  script:
    - docker build --pull -t $IMAGE_HUGO ob-hugo
    - docker push $IMAGE_HUGO
    - docker build --pull -t $IMAGE_OB ob
    - docker push $IMAGE_OB
